name       : python-markdown-math
version    : 0.6
release    : 1
source     :
    - https://files.pythonhosted.org/packages/78/e1/24021b30466ca2985352ec1f15b3cb38e0b62ba742c46820c33ddf7114a8/python-markdown-math-0.6.tar.gz : c68d8cb9695cb7b435484403dc18941d1bad0ff148e4166d9417046a0d5d3022
license    : MIT
component  : programming.python
summary    : This extension adds math formulas support to Python-Markdown
description: |
    This extension adds math formulas support to Python-Markdown.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-markdown
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
