name       : python-markdown-math
version    : '0.6'
release    : 2
source     :
    - https://pypi.python.org/packages/source/p/python-markdown-math/python-markdown-math-0.6.tar.gz : c68d8cb9695cb7b435484403dc18941d1bad0ff148e4166d9417046a0d5d3022
license    : MIT
component  : programming.python
summary    : This extension adds math formulas support to Python-Markdown
description: |
    This extension adds math formulas support to Python-Markdown.
builddeps  :
    - pkgconfig(python3)
    - python-markdown
rundeps    :
    - python-markdown
setup      : |
    %patch -p1 < $pkgfiles/Fix-deprecation-warnings-with-Python-Markdown-3.x.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
